services:
  moments:
    image: kingwrcy/moments:latest
    container_name: moments
    restart: always
    environment:
      PORT: 37892
      JWT_KEY: $JWT_KEY
    ports:
      - 37892:37892
    volumes:
      - ./moments:/app/data # 持久化数据到当前目录的 moments 文件夹
